### ISSUE TITLE
[Client] Frontend CI가 실패한다

### ISSUE THREAD

**Issue by leegwae** [blacktokkies/toquiz#161]
https://github.com/blacktokkies/toquiz/actions/runs/4574901894

`yarn shared install`에서 실패한다.

```
The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
```

### 디렉토리 구조

yarn workspace를 사용하여 모노 레포 구성하고 있음.

```
|--client
  |--package.json
|--shared
  |--package.json
|--package.json
|--yarn.lock
```

### root/package.json

```json
{
  "name": "toquiz",
  "version": "1.0.0",
  "private": true,
  "repository": "https://github.com/blacktokkies/toquiz.git",
  "license": "MIT",
  "main": "index.js",
  "workspaces": {
    "packages": [
      "shared",
      "client",
      "server"
    ],
    "nohoist": [
      "server",
      "server/**"
    ]
  },
  "scripts": {
    "root": "yarn workspace -W",
    "server": "yarn workspace server",
    "shared": "yarn workspace shared",
    "client": "yarn workspace client"
  },
  "engines": {
    "npm": "please use yarn"
  }
}
```

### client/package.json

```json
{
  "name": "client",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "preinstall": "yarn workspace shared install && yarn workspace shared build",
    "dev": "vite",
    "dev:proxy": "vite --mode proxy",
    "build": "tsc && vite build",
    "preview": "vite preview",
    "lint": "eslint \"src/**/*.{ts,tsx}\" --fix",
    "test": "vitest",
    "test:ui": "vitest --ui",
    "coverage": "vitest run --coverage"
  },
  "dependencies": {
    "@tanstack/react-query": "^4.24.4",
    "cross-fetch": "^3.1.5",
    "detect-node": "^2.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.8.0",
    "shared": "1.0.0",
    "validator": "^13.9.0",
    "zustand": "^4.3.4"
  },
  "devDependencies": {
    "@tanstack/react-query-devtools": "^4.24.4",
    "@testing-library/dom": "^9.0.1",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^14.4.3",
    "@types/detect-node": "^2.0.0",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
    "@types/validator": "^13.7.12",
    "@typescript-eslint/eslint-plugin": "^5.50.0",
    "@typescript-eslint/parser": "^5.50.0",
    "@vitejs/plugin-react": "^3.0.0",
    "@vitest/coverage-c8": "^0.29.2",
    "@vitest/ui": "^0.29.2",
    "autoprefixer": "^10.4.13",
    "eslint": "^8.33.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-config-standard-with-typescript": "^34.0.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-n": "^15.6.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-tailwindcss": "^3.8.3",
    "eslint-plugin-testing-library": "^5.10.2",
    "eslint-plugin-vitest": "^0.0.54",
    "jsdom": "^21.1.1",
    "msw": "^1.0.0",
    "postcss": "^8.4.21",
    "prettier": "2.8.3",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.9.3",
    "vite": "^4.0.0",
    "vite-plugin-checker": "^0.5.5",
    "vite-tsconfig-paths": "^4.0.5",
    "vitest": "^0.29.2"
  },
  "msw": {
    "workerDirectory": "./public"
  }
}
```

### shared/package.json

```json
{
  "name": "shared",
  "version": "1.0.0",
  "main": "dist/cjs/index.js",
  "exports": {
    ".": {
      "require": {
        "default": "./dist/cjs/index.js",
        "types": "./dist/cjs/index.d.ts"
      },
      "import": {
        "default": "./dist/esm/index.js",
        "types": "./dist/esm/index.d.ts"
      }
    }
  },
  "license": "MIT",
  "scripts": {
    "prebuild": "rm -rf dist",
    "build": "yarn build:cjs & yarn build:esm",
    "build:cjs": "tsc -p tsconfig.cjs.json",
    "build:esm": "tsc -p tsconfig.esm.json",
    "lint": "eslint \"src/**/*.ts\" --fix"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.49.0",
    "@typescript-eslint/parser": "^5.49.0",
    "eslint": "^8.33.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-config-standard-with-typescript": "^33.0.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-n": "^15.6.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.1.1",
    "prettier": "2.8.3",
    "typescript": "^4.9.4"
  }
}
```

### .github/workflows/test.fe.yml

```
name: Frontend CI

on:
  pull_request:
    branches: [dev]
    paths:
      - "client/**"

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node: [18.x]
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install shared dependencies
        run: yarn shared install --immutable --immutable-cache --check-cache
      
      - name: Build shared code
        run: yarn shared build
      
      - name: Install client dependencies
        run: yarn client install --immutable --immutable-cache --check-cache
        
      - name: Build production bundle
        run: yarn client build
        
      - name: Run tests
        run: yarn client test
```
