### ISSUE TITLE
웹 폰트 최적화하기

### ISSUE THREAD

**Issue by leegwae** [blacktokkies/toquiz#479]
## 🤸‍♂️ 목표

https://github.com/blacktokkies/toquiz-client/blob/7a2779a7c95e2f3a421ada65af7758ddae25b9c0/src/index.css#L1

위와 같이 Web Font를 사용하고 있다. `@import`는 병렬로 다운로드되지 않으므로 렌더링을 블로킹한다. `@import`을 없애보자.

## ✨ `@font-face`로 선언하기

`@import`는 의존성을 순차적으로 다운로드하지만, `@font-face`는 폰트를 병렬로 다운로드할 수 있다. 또한 스타일에서 참조될 때에만 폰트를 다운로드한다. `font-style`, `font-weight` 등 폰트를 세밀하게 설정해줄 수도 있다.

```css
@font-face {
  font-family: 'Noto Sans KR';
  font-style: normal;
  font-weight: 400;
  src: url(/fonts/NotoSansKR-Regular.ttf) format('truetype');
}

@font-face {
  font-family: 'Noto Sans KR';
  font-style: normal;
  font-weight: 599;
  src: url(/fonts/NotoSansKR-Medium.ttf) format('truetype');
}
```

한편 CDN을 이용하지 않고 정적 에셋으로 제공해줄 거다. 구글 CDN으로 날릴 때의 DNS lookup 비용을 줄이고 데이터 수집을 피할 수 있다.

## ✨ 폰트 파일 크기 줄이기

이제 폰트 파일 크기를 줄여보자

### 1. 필요한 굵기만 다운로드하기

[Google Fonts Noto Sans KR](https://fonts.google.com/noto/specimen/Noto+Sans+KR?query=noto+sans)에서 원하는 굵기만 다운로드했다. toquiz의 경우 400, 500, 600, 700이다.

### 2. subset 만들기

> 출처
https://boramyy.github.io/dev/front-end/etc/font/

toquiz에서 사용할 언어는 아무래도 한정적이다. 사용할만한 문자만 포함시킨 subset 폰트를 만들자. 위 출처의 포스트를 참고한다.

![원본](https://github.com/blacktokkies/toquiz-client/assets/57662010/654545ac-6ed7-477b-9606-604dda402794)
![subset](https://github.com/blacktokkies/toquiz-client/assets/57662010/42562fee-0429-4857-b463-c4ce7d2bcef9)

아래가 subset이다. 크기가 엄청나게 줄었다.

### 3. 모던 파일 포맷 사용하기

woff는 전통적인 폰트 파일 포맷(ttf)보다 압축률이 뛰어나다. woff2는 woff보다도 압축률이 좋다. subset 언어를 woff, woff2로 변환하니 파일 크기는 원본에 비해 엄청나게 줄어든다.

![fomat](https://github.com/blacktokkies/toquiz-client/assets/57662010/dd6726d0-dbea-4623-ba4e-e8a31ab3c9da)

subset을 만들 때 subset 만들기의 출처에 있는 포스트를 참고하면, woff, woff2도 자동으로 만들 수 있다. eot는 tff를 eot로 바꾸어주는 online converter 아무거나 사용했다. 

## FOIT 대신 FOUT

- `FOIT(Flash of Invisible Text)`는 웹 폰트가 로드되기 전까지 웹 폰트를 필요로하는 컨텐츠를 렌더링하지 않다가 로드가 되면 컨텐츠를 보여준다.
- `FOUT(Flash of Unstyled Text)`는 웹 폰트가 로드되기 전까지는 기본 폰트를 보여주고 웹 폰트가 로드되면 reflow한다.

FOIT는 치명적이다. 중요한 컨텐츠가 나타나지 않으면 큰일이다. FOUT를 적용하려면 `@font-face`의 속성 `font-display: swap;`를 사용하면 된다.

## ✨ 완성

```css
@font-face {
  font-family: 'Noto Sans KR';
  font-style: normal;
  font-weight: 400;
  src: url(/fonts/NotoSansKR-Regular.eot),
    url(/fonts/NotoSansKR-Regular.woff2) format('woff2'),
    url(/fonts/NotoSansKR-Regular.woff) format('woff'),
    url(/fonts/NotoSansKR-Regular.ttf) format('truetype');
  font-display: swap;
}

@font-face {
  font-family: 'Noto Sans KR';
  font-style: normal;
  font-weight: 500;
  src: local('NotoSansKR-Medium'), url(/fonts/NotoSansKR-Medium.eot),
    url(/fonts/NotoSansKR-Medium.woff2) format('woff2'),
    url(/fonts/NotoSansKR-Medium.woff) format('woff'),
    url(/fonts/NotoSansKR-Medium.ttf) format('truetype');
  font-display: swap;
}

/* 생략 */
```

## 참고

- [웹폰트 사용하기 (웹폰트 101)](https://wit.nts-corp.com/2017/02/13/4258)
- [웹 폰트 사용과 최적화의 최근 동향](https://d2.naver.com/helloworld/4969726)
- [웹 폰트 로딩을 더 빠르게 하는 방법](https://yceffort.kr/2021/06/ways-to-faster-web-fonts)
- [https://velog.io/@vnthf/웹폰트-최적화-하기](https://velog.io/@vnthf/%EC%9B%B9%ED%8F%B0%ED%8A%B8-%EC%B5%9C%EC%A0%81%ED%99%94-%ED%95%98%EA%B8%B0)
- [웹폰트 더빠르게 로드하기](https://boramyy.github.io/dev/front-end/etc/font/)
- [글꼴 권장사항](https://web.dev/articles/font-best-practices?hl=ko)
